# Uncomment the next 13.49.0'

target 'Mobile Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mobile Test 
  pod 'OHHTTPStubs/Swift'

  target 'Mobile TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
